apiVersion: v1
kind: Service
metadata:
  name: {{ include "pplale-room-server.fullname" . }}
  labels:
    {{- include "pplale-room-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pplale-room-server.selectorLabels" . | nindent 4 }}
    # 同じリリースの Redis の Pod を選ばないようにする。
    app.kubernetes.io/component: server
