// A learned position value for さいきょう, trained on match outcomes. Node only (no browser).
//   npm run cpu:value -- collect [games=40000] [share of turns kept=0.5]
//   npm run cpu:value -- train [hidden=32] [epochs=4]
//   npm run cpu:value -- adopt
// collect: つよい plays itself (with an occasional random move, so off-plan positions are covered)
//   and sampled turn starts are stored with who won, in scripts/value-data.bin (not committed).
// train: fits the network of src/ai/value.ts and writes scripts/value-model.json (not committed).
//   Positions of the same match stay together in either the training or the validation part.
// adopt: copies that model into src/ai/value-model.ts, which さいきょう uses. Do it only when
//   `createMaster({ evaluate: createValueEvaluator(model) })` clearly beats the current さいきょう
//   over a few hundred matches it was not chosen on.
// The sampling and the fitting themselves are in src/ai/value-train.ts (shared with the CPU server).
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import { isMainThread, parentPort, Worker } from 'node:worker_threads';
import { selfPlayPositions, trainValue, valueData, VALUE_ROW } from '../dist/ai/value-train.js';
import { catalog } from './catalog.mjs';

const dataFile = new URL('./value-data.bin', import.meta.url), modelFile = new URL('./value-model.json', import.meta.url);
const bytes = array => Buffer.from(array.buffer, array.byteOffset, array.byteLength);

if (!isMainThread) {
  parentPort.on('message', ({ seeds, share }) => {
    const { x, y, match } = valueData(seeds.flatMap(seed => {
      const sample = selfPlayPositions(catalog, seed, share);
      return sample ? [{ id: seed, ...sample }] : [];
    }));
    parentPort.postMessage({ x, y, match }, [x.buffer, y.buffer, match.buffer]);
  });
} else if (process.argv[2] === 'collect') {
  const [games = 40000, share = 0.5] = process.argv.slice(3).map(Number);
  const started = Date.now(), workers = Array.from({ length: Math.max(1, os.cpus().length - 1) }, () => new Worker(new URL(import.meta.url)));
  // Seeds from 1e6: apart from the matches used to compare levels (arena) and to train weights.
  const seeds = Array.from({ length: games }, (_, i) => 1_000_000 + i), chunk = 100;
  const parts = [];
  await Promise.all(workers.map(worker => new Promise(done => {
    const next = () => seeds.length ? worker.postMessage({ seeds: seeds.splice(0, chunk), share }) : done(worker.terminate());
    worker.on('message', part => { parts.push(part); next(); });
    next();
  })));
  const count = parts.reduce((sum, part) => sum + part.y.length, 0);
  writeFileSync(dataFile, Buffer.concat([new Uint32Array([VALUE_ROW, count]), ...parts.map(p => p.match), ...parts.map(p => p.y), ...parts.map(p => p.x)].map(bytes)));
  const wins = parts.reduce((sum, part) => sum + part.y.reduce((a, b) => a + b, 0), 0);
  console.log(`${count} positions from ${games} matches (side 0 won ${(wins / count * 100).toFixed(1)}%), ${Math.round((Date.now() - started) / 1000)}s`);
} else if (process.argv[2] === 'train') {
  if (!existsSync(dataFile)) throw new Error('no data: run `collect` first');
  const [hidden = 32, epochs = 4] = process.argv.slice(3).map(Number);
  const file = readFileSync(dataFile), [row, count] = new Uint32Array(file.buffer, file.byteOffset, 2);
  if (row !== VALUE_ROW) throw new Error('the data was collected with other features: run `collect` again');
  const copy = (Type, offset, length) => new Type(file.buffer.slice(file.byteOffset + offset, file.byteOffset + offset + length * Type.BYTES_PER_ELEMENT));
  const data = { match: copy(Uint32Array, 8, count), y: copy(Uint8Array, 8 + count * 4, count), x: copy(Float32Array, 8 + count * 5, count * VALUE_ROW) };
  const show = (name, fit) => console.log(`${name.padEnd(18)}  loss ${fit.loss.toFixed(4)}  accuracy ${(fit.accuracy * 100).toFixed(1)}%`);
  const result = trainValue(data, { hidden, epochs, onEpoch: (epoch, fit) => show(`epoch ${epoch}`, fit) });
  show('hand-written value', result.baseline);
  writeFileSync(modelFile, JSON.stringify(result.model) + '\n');
  console.log(`\n${result.training} training / ${result.validation} validation positions`);
  console.log(`best validation loss ${result.fit.loss.toFixed(4)} (accuracy ${(result.fit.accuracy * 100).toFixed(1)}%), scale ${result.model.scale} → scripts/value-model.json`);
} else if (process.argv[2] === 'adopt') {
  const model = readFileSync(modelFile, 'utf8').trim();
  writeFileSync(new URL('../src/ai/value-model.ts', import.meta.url), `// Generated by \`npm run cpu:value -- adopt\`. Do not edit: retrain instead (scripts/value.mjs).
import type { ValueModel } from './value.ts';

export const valueModel: ValueModel = ${model};
`);
  console.log('src/ai/value-model.ts updated');
} else console.log('usage: npm run cpu:value -- collect [games] [share of turns] | train [hidden] [epochs] | adopt');
