export * from './model.ts';
export { applyCommand } from './commands/index.ts';
export { newGame, validateDeck } from './setup.ts';
export { restoreGame } from './snapshot.ts';
export { actingSides, cpuCommand, cpuLevels, cpuStrategies, determinize, evaluate, defaultWeights, legalMoves } from './ai/index.ts';
export type { CpuDecision, CpuLevel, CpuOptions, CpuStrategy, Move, Weights } from './ai/index.ts';
export { attackOf, costOf, hpOf, maxPp, spawnCard } from './core/cards.ts';
export { canAttack } from './core/combat.ts';
export { skillsFor } from './playables/skills.ts';
export type { SkillScript } from './playables/skills.ts';
export { scriptOf } from './cards/registry.ts';
export type { CardScript, OpDef } from './cards/types.ts';
export { attackTargets, isRevealable, pendingView } from './view.ts';
export type { PendingView } from './view.ts';
