export { cpuLevels, cpuProfiles } from './ai/profiles.ts';
export * from './model.ts';
export { applyCommand } from './commands/index.ts';
export { newGame, validateDeck } from './setup.ts';
export { deckRuleErrors, defaultMatchRules, describeMatchRules, fruitNames, fruits, isExtendedPlayable, parseMatchRules, playableNow } from './rules.ts';
export type { Fruit, MatchRules } from './rules.ts';
export { restoreGame } from './snapshot.ts';
export { buildPosition, checkPosition, decodePosition, encodePosition, parsePosition, positionOf } from './position.ts';
export type { Position, PositionHandCard, PositionSide, PositionUnit } from './position.ts';
export { editGame, printedKeywords } from './edit.ts';
export type { BoardEdit, EditZone } from './edit.ts';
export { actingSides, cpuCommand, cpuStrategies, createHard, createMaster, createValueEvaluator, determinize, evaluate, defaultWeights, findLethal, legalMoves, playMatch, randomStrawberryDeck, valueFeatures, valueLayout, valueLogit } from './ai/index.ts';
export type { CpuDecision, CpuLevel, CpuOptions, CpuStrategy, Evaluator, LethalOptions, LethalResult, MatchOptions, MatchResult, Move, TurnSearchOptions, ValueModel, Weights } from './ai/index.ts';
export { attackOf, availablePpMaximum, costOf, hpOf, maxPp, spawnCard } from './core/cards.ts';
export { canAttack } from './core/combat.ts';
export { skillsFor } from './playables/skills.ts';
export type { SkillScript } from './playables/skills.ts';
export { implementedCard, scriptOf } from './cards/registry.ts';
export { fruitsOf } from './core/protection.ts';
export { exSkillInfo } from './playables/exSkills.ts';
export type { CardScript, OpDef } from './cards/types.ts';
export { changesBetween, instanceFields, playerFields, stateFields, zones } from './changes.ts';
export type { Change, ChangeKind, Place, Zone } from './changes.ts';
export { attackTargets, canPlay, isRevealable, pendingView, skillBlocked } from './view.ts';
export type { PendingView } from './view.ts';
export { HIDDEN_CARD, viewFor } from './redact.ts';
